users/urls.py
"""Users URL Configuration"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # include default authorization
    path('', include('django.contrib.auth.urls')),
    # registration
    path('register/', views.register, name='register')
]

web_notepad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('web_notes.urls'))
]

web_notes/urls.py
"""web_notes URL Configuration"""

from django.urls import path
from . import views

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


app_name = 'web_notes'
urlpatterns = [
    # Homepage
    path('', views.index, name='index'),

    # page with topics
    path('topics/', views.topics, name='topics'),

    # page with single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # page for adding new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    # page for new note
    path('new_note/<int:topic_id>/', views.new_note, name='new_note'),

    # page for editing notes
    path('edit_note/<int:note_id>/', views.edit_note, name='edit_note'),

]

users/models.py
from django.db import models

# Create your models here.

web_notes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Additional information
# Django API, making queries https://docs.djangoproject.com/en/4.1/topics/db/queries/
# possible types of fields https://docs.djangoproject.com/en/4.1/ref/models/fields/


class Topic(models.Model):
    """Topics of notes to save in DB"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        """return text"""
        return self.text

class Note(models.Model):
    """Notes"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'notes'

    def __str__(self):
        """return string value"""
        if len(self.text) <= 50:
            return self.text
        else:
            return f"{self.text[:50]}..." #return the firts 50 symbols
    

web_notes/forms.py
from django import forms
from .models import Topic, Note

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.

def register(request):
    """register new user"""
    if request.method != 'POST':
        # shows empty form
        form = UserCreationForm()
    else:
        # perform filed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()

            # login and redirect to home
            login(request, new_user)
            return redirect('web_notes:index')

    # shows empty or incorrect form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

web_notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Topic, Note
from .forms import TopicForm, NoteForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.

def index(request):
    """Homepage of application Web notes"""
    return render(request, 'web_notes/index.html')


@login_required
def topics(request):
    """shows topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('-date_added')
    context = {'topics': topics}

    return render(request, 'web_notes/topics.html', context)

@login_required
def topic(request, topic_id):
    """shows single topic and related notes"""
    # topic = Topic.objects.get(id=topic_id)
    topic = get_object_or_404(Topic, id=topic_id)

    check_topic_owner(topic, request)
    
    # there are 2 ways to select data from the second table: note_set or filter(). 
    # "note" - is dymanic name, generated for object Note, described in models.py
    notes = topic.note_set.order_by('-date_added')

    # # get is limited to 1 result, if you're making a query that matches more than one element you should use filter
    # notes = Note.objects.filter(topic_id=topic.id)

    context = {'topic': topic, 'notes': notes}

    return render(request, 'web_notes/topic.html', context)

@login_required
def new_topic(request):
    """New topic creation"""
    if request.method != 'POST':
        # data was not sent, empty form
        form = TopicForm()
    else:
        # data was sent
        form = TopicForm(data=request.POST)
        if form.is_valid():
            newtopic = form.save(commit=False)
            newtopic.owner = request.user
            newtopic.save()
            return redirect('web_notes:topics')

    # show form
    context = {'form': form}
    return render(request, 'web_notes/new_topic.html', context)

@login_required
def new_note(request, topic_id):
    """creating of new notes"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request)

    if request.method != 'POST':
        # data was not send
        form = NoteForm()
    else:
        # data was sent
        form = NoteForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('web_notes:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(request, 'web_notes/new_note.html', context)

@login_required
def edit_note(request, note_id):
    """editing of notes"""
    note = Note.objects.get(id=note_id)
    topic = note.topic
    check_topic_owner(topic, request)

    if request.method != 'POST':
        # data was not send
        form = NoteForm(instance=note)
    else:
        # data was sent
        form = NoteForm(instance=note, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('web_notes:topic', topic_id=topic.id)

    context = {'note': note, 'topic': topic, 'form': form}
    return render(request, 'web_notes/edit_note.html', context)

def check_topic_owner(topic, request):
    """check topic owner"""
    if topic.owner != request.user:
        raise Http404

web_notes/templates/web_notes/base.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="icon" href="{% static 'web_notes/favicon.ico' %}">
    <title>Web notepad</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'web_notes:index' %}">Web Notepad</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'web_notes:topics' %}">Topics</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username|title }}. </span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

web_notes/templates/web_notes/edit_note.html
{% extends 'web_notes/base.html' %}
{% load bootstrap4 %}


{% block page_header %} 
    <h2>Edit note of topic <a href="{% url 'web_notes:topic' topic.id %}">{{ topic }}</a> </h2>
{% endblock page_header %}


{% block content %}
    <form action="{% url 'web_notes:edit_note' note.id %}" method="post" class="form">
        {% csrf_token %}

        {% bootstrap_form form %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>
{% endblock content %}

web_notes/templates/web_notes/index.html
{% extends 'web_notes/base.html' %}

{% block page_header %}

    <div class="jumbotron">
        {% if user.is_authenticated %}
            <h1 class="display-3">Welcome, {{ user.username|title }}</h1>
        {% else %}
            <h1 class="display-3">Write your notes anytime and anywhere</h1>
        {% endif %}

        <p class="lead">This is simple <a href="https://github.com/Ranorien/Web_notepad" target="_blank">open source</a> web notepad. 
            You can save your notes and access them any time from different devices and from different places of the world.
        </p>
        
        <hr class="my-2">
        <p class="lead">
            {% if user.is_authenticated %}
                <a class="btn btn-primary btn-lg" href="{% url 'web_notes:topics' %}" role="button">Write notes &raquo;</a>
            {% else %}
                <a class="btn btn-primary btn-lg" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
            {% endif %}
        </p>
    </div>

{% endblock page_header %}

{% block content %} 

{% endblock content %}

web_notes/templates/web_notes/new_note.html
{% extends 'web_notes/base.html' %}
{% load bootstrap4 %}

{% block page_header %} 
    <h2>Add new note to topic: <a href="{% url 'web_notes:topic' topic.id %}">{{ topic }}</a> </h2>
{% endblock page_header %}


{% block content %}
    <form action="{% url 'web_notes:new_note' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">Add note</button>
        {% endbuttons %}
    </form>

{% endblock content %}

web_notes/templates/web_notes/new_topic.html
{% extends 'web_notes/base.html' %}
{% load bootstrap4 %}

{% block page_header %} 
    <h2>Add new topic</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'web_notes:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">Add topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}

web_notes/templates/web_notes/topic.html
{% extends 'web_notes/base.html' %}

{% block page_header %}
    <div class="row">
        <div class="col-md-auto">
            <a href="{% url 'web_notes:new_note' topic.id %}" class="btn btn-secondary">New note</a>
        </div>
        <div class="col-md-auto">
            <h2>{{ topic }}</h2> 
        </div>
    </div>
{% endblock page_header %} 


{% block content %}
    {% for note in notes %}
        <div class="card mb-3">
            <div class="card-header">
                {{ note.date_added|date:'M d, Y H:i' }}
                <a href="{% url 'web_notes:edit_note' note.id %}">edit</a> 
            </div>
            <div class="card-body">
                <p class="card-text">{{ note.text|linebreaks}}</p>
            </div>
        </div>
    {% empty %}
        <h2>There are no entries for this topic yet</h2>
    {% endfor %}

{% endblock content %}

web_notes/templates/web_notes/topics.html
{% extends 'web_notes/base.html' %}

{% block page_header %} 
    <a href="{% url 'web_notes:new_topic' %}" class="btn btn-secondary">Add new topic</a> 
{% endblock page_header %}
    
{% block content %}

    {% for topic in topics %}
        <div class="list-group">
            <a href="{% url 'web_notes:topic' topic.id %}" class="list-group-item list-group-item-action">{{ topic }}</a>
        </div>
    {% empty %}
        <h3>No topics have been added yet</h3>
    {% endfor %}
    
{% endblock content %}